---
services:
  s-ui:
    image: dxbwala/s-ui
    container_name: s-ui
    hostname: "s-ui"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "2080:2080"
      - "2035:2035"
    networks:
      - s-ui
    entrypoint: "./entrypoint.sh"

networks:
  s-ui:
    driver: bridge
  